### PR TITLE
Remove reply queue on timeout

### PR DESCRIPTION
**Pull request by kozzztya**
It would be great to remove reply queue after timeout error.
@tjmehta What do you think maybe we can remove reply queue once at the end of request function?

### CODE REVIEW

**Comment by tjmehta** [comment]
Reply queues should not be persisted (they should be deleted when their parent channel is deleted). Are you providing custom options to the reply queue?

**Comment by kozzztya** [comment]
>  Are you providing custom options to the reply queue?  

Only `timeout` option. And after `TimeoutError` reply queue still exists.
I developing a feature that retries message consuming is a case of error. For example I make a request to a microservice. But the microservice crashed. If there is no reply in 2 seconds I repeat the request in 30 seconds. So after 100 requests retries, I have 100 reply queues. It is not cool.

Is this PR is OK for you? I will fix tests if you agree to accept it.

**Comment by tjmehta** [comment]
I see the problem you are having!

1) We should probably explicitly close the queue when we close the channel:
https://github.com/tjmehta/amqplib-rpc/blob/master/lib/request.js#L158
https://github.com/tjmehta/amqplib-rpc/blob/master/lib/request.js#L168

2) Do you think using the `autoDelete` on the reply queue would be a better default than `exclusive`?
http://www.squaremobius.net/amqp.node/channel_api.html#channel_assertQueue
https://github.com/tjmehta/amqplib-rpc/blob/master/lib/request.js#L64

3) Let's discuss the replyQueue naming in another PR: #14

**Comment by kozzztya** [comment]
> 1. Does delete queue throw an error if the queue doesn't exist?

According to the docs:
Naming a queue that doesn't exist will result in the server closing the channel, to teach you a lesson (except in RabbitMQ version 3.2.0 and after).

> 2. Do you think using the autoDelete on the reply queue would be a better default than exclusive?

`autoDelete` always works well for queue temporary queues. 
In my experience `exclusive` option causes errors on containers restart, so I avoid using it. But for replyQueue it's fine.

**Pull request closed without merging**
