### PR TITLE
Fix: always delete replyQueue

### PR DESCRIPTION
**Pull request by tjmehta**

### CODE REVIEW

**Comment by tjmehta** [comment]
@kozzztya I had some time to knock out (1). Let me know if this patch works for you.

Also, please tell me your thoughts on the rest: https://github.com/tjmehta/amqplib-rpc/pull/13#issuecomment-284540017.

Thanks!

**Comment by kozzztya** [comment]
Yes, it works great, thanks!

**Comment by kozzztya** [comment]
@tjmehta Is it ready to merge and publish in npm?

**Comment by tjmehta** [comment]
Hey kozzzta, sorry for the delay. Was just waiting on your confirmation.

**Comment by tjmehta** [comment]
@kozzztya published: amqplib-rpc@2.0.4

**Pull request merged**
